### PR TITLE
API: add CORS to GeoJSON and JSON

### PR DESCRIPTION
**Pull request by Abbe98**

### CODE REVIEW

**Comment by Abbe98** [comment]
> Why not just use jsonp? What are the benefits of enabling CORS?

 - JSONP is implemented with a `<script>` tag, executing actual JavaScript on another domain.
 - The `<script>` tag will result in a synchronous behavior. 
 - JSONP in incompatible with fancy new things such as `Content-Security-Policy`.

Generally JSONP is something you should only use when you need to support relay old browsers.

> Would you really want to whitelist all domains. Doesn't that defeat the purpose of CORS?

I don't see the need to not allow certain sites in the case of this API. I guess it would be hard to create a list of sites to be allowed?

**Comment by lokal-profil** [comment]
OK. After looking at [T62835](https://phabricator.wikimedia.org/T62835) as well I'm convinced this shouldn't be a problem for the json and geojson formats.

Would you mind moving the header to `Format.php` and `FormatGeojson.php` respectively though (where the content-type headers are).

**Comment by Abbe98** [comment]
There is two more commits then what would make sense for this commit, I suggest you squash merges it.

**Comment by lokal-profil** [comment]
And deployed

**Comment by Abbe98** [comment]
Great thanks!

**Pull request merged**
